---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install essential admin tools
  apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - net-tools
      - unattended-upgrades
      - git
    state: present

- name: Set timezone
  timezone:
    name: America/Chicago
